version: "3.8"
services:
  h3-postgresql:
    build:
      context: .
      args:
        - PG_H3_VERSION=4.1.3
    container_name: h3-postgresql
    env_file: ../src/h3tiler/.env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - h3-postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: on-failure

volumes:
  h3-postgresql:
